server {
    listen 80;
    server_name _;

    # 外部 nginx 保留了 /solar/ 前缀
    # /solar/ → /usr/share/nginx/html/
    location /solar/ {
        alias /usr/share/nginx/html/;
        index index.html;
    }

    location / {
        return 301 /solar/;
    }
}
